// Europe-wide MeteoAlarm adapter. The aggregate Atom URL is not published; aggregate country Atom feeds.
export default async function handler(req,res){
 const countries=[["andorra","Andorra",[42.51,1.52]],["austria","Austria",[47.52,14.55]],["belgium","Belgium",[50.5,4.47]],["bulgaria","Bulgaria",[42.73,25.49]],["croatia","Croatia",[45.1,15.2]],["czechia","Czechia",[49.82,15.47]],["denmark","Denmark",[56,10]],["estonia","Estonia",[58.6,25]],["finland","Finland",[64,26]],["france","France",[46.6,2.2]],["germany","Germany",[51.17,10.45]],["greece","Greece",[39.07,21.82]],["hungary","Hungary",[47.16,19.5]],["ireland","Ireland",[53.3,-8]],["italy","Italy",[42.8,12.5]],["latvia","Latvia",[56.9,24.6]],["lithuania","Lithuania",[55.2,23.9]],["netherlands","Netherlands",[52.13,5.29]],["norway","Norway",[62,10]],["poland","Poland",[52,19.15]],["portugal","Portugal",[39.5,-8]],["romania","Romania",[45.94,24.97]],["slovakia","Slovakia",[48.7,19.7]],["slovenia","Slovenia",[46.15,14.99]],["spain","Spain",[40.2,-3.7]],["sweden","Sweden",[62,15]],["switzerland","Switzerland",[46.8,8.2]],["ukraine","Ukraine",[48.38,31.17]],["united-kingdom","United Kingdom",[54.5,-2.5]]];
 const decode=s=>String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
 const clean=v=>decode(v).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
 const read=(b,names)=>{for(const n of names){const m=b.match(new RegExp('<(?:[\\w.-]+:)?'+n+'\\b[^>]*>([\\s\\S]*?)<\\/(?:[\\w.-]+:)?'+n+'>','i'));if(m)return clean(m[1])}return ''};
 const geometry=b=>{let n=read(b,['point','pos']).split(/\s+/).map(Number).filter(Number.isFinite);if(n.length>=2)return{lat:n[0],lon:n[1],precision:'exact'};n=read(b,['box']).split(/\s+/).map(Number).filter(Number.isFinite);if(n.length>=4)return{lat:(n[0]+n[2])/2,lon:(n[1]+n[3])/2,precision:'area'};n=read(b,['polygon']).split(/\s+/).map(Number).filter(Number.isFinite);if(n.length>=4){let a=0,o=0,c=0;for(let i=0;i+1<n.length;i+=2){a+=n[i];o+=n[i+1];c++}if(c)return{lat:a/c,lon:o/c,precision:'area'}}return null};
 const parse=(xml,country,i)=>{const entries=xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[];return entries.map((b,n)=>{let g=geometry(b)||{lat:country[2][0],lon:country[2][1],precision:'approx'};const title=read(b,['title','event'])||'Aviso meteorológico',area=read(b,['areaDesc','area','featureName','location'])||country[1],time=read(b,['updated','published','effective'])||null,detail=read(b,['summary','description','content']),severity=read(b,['severity','awareness_level']),href=(b.match(/<link\b[^>]*href=["']([^"']+)["']/i)||[])[1]||'https://www.meteoalarm.org/';return{id:'eu-'+country[0]+'-'+Buffer.from(title+'|'+area+'|'+(time||'')+'|'+n).toString('base64url').slice(0,42),name:title,type:'weather',lat:g.lat,lon:g.lon,locationPrecision:g.precision,area,time,severity,detail:detail.slice(0,900),source:'METEOALARM-EU',country:country[1],scope:'europe',kind:'official',url:decode(href)}})};
 try{
  const results=await Promise.allSettled(countries.map(async c=>{const r=await fetch('https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-'+c[0],{headers:{accept:'application/atom+xml,application/xml,text/xml,*/*'},signal:AbortSignal.timeout(9000)});if(!r.ok)throw Error('HTTP '+r.status);return{c,xml:await r.text()}}));
  const events=[],failed=[];
  results.forEach((r,i)=>{if(r.status==='fulfilled')events.push(...parse(r.value.xml,r.value.c,i));else failed.push(countries[i][0])});
  const unique=[...new Map(events.map(e=>[e.id,e])).values()];
  res.setHeader('Cache-Control','s-maxage=120,stale-while-revalidate=300');
  return res.status(200).json({source:'METEOALARM-EU',count:unique.length,countriesLoaded:countries.length-failed.length,countriesFailed:failed,events:unique});
 }catch(e){return res.status(502).json({source:'METEOALARM-EU',error:String(e.message||e),events:[]})}
}