export default async function handler(req,res){
const feedUrl='https://feeds.meteoalarm.org/feeds/meteoalarm-legacy-atom-spain';
const centers={andalucia:[37.38,-5.98],aragon:[41.65,-0.89],asturias:[43.36,-5.85],cantabria:[43.46,-3.81],castillayleon:[41.65,-4.72],castillalamancha:[39.86,-4.03],cataluna:[41.59,1.52],catalunya:[41.59,1.52],comunitatvalenciana:[39.47,-0.38],valencia:[39.47,-0.38],extremadura:[38.88,-6.97],galicia:[42.58,-8.13],illesbalears:[39.57,2.65],baleares:[39.57,2.65],canarias:[28.29,-16.63],larioja:[42.29,-2.54],navarra:[42.81,-1.65],paisvasco:[43,-2.5],euskadi:[43,-2.5],murcia:[37.99,-1.13],madrid:[40.42,-3.70],ceuta:[35.89,-5.32],melilla:[35.29,-2.94],barcelona:[41.39,2.17],tarragona:[41.12,1.24],girona:[41.98,2.82],lleida:[41.62,.62],valencia:[39.47,-.38],alicante:[38.35,-.48],castellon:[39.99,-.05],sevilla:[37.39,-5.98],malaga:[36.72,-4.42],cadiz:[36.53,-6.29],granada:[37.18,-3.60],zaragoza:[41.65,-.89],bilbao:[43.26,-2.94],oviedo:[43.36,-5.85],santander:[43.46,-3.81],coruna:[43.36,-8.41],vigo:[42.24,-8.72],pamplona:[42.81,-1.65],valladolid:[41.65,-4.72],toledo:[39.86,-4.03],merida:[38.92,-6.34],palma:[39.57,2.65],tenerife:[28.46,-16.25],laspalmas:[28.12,-15.44]};
const decode=s=>String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&');
const clean=v=>decode(v).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const read=(b,names)=>{for(const n of names){const m=b.match(new RegExp('<(?:[\\w.-]+:)?'+n+'\\b[^>]*>([\\s\\S]*?)<\\/(?:[\\w.-]+:)?'+n+'>','i'));if(m)return clean(m[1])}return ''};
const geometry=b=>{let n=read(b,['point','pos']).split(/\s+/).map(Number).filter(Number.isFinite);if(n.length>=2)return{lat:n[0],lon:n[1],locationPrecision:'exact'};n=read(b,['box']).split(/\s+/).map(Number).filter(Number.isFinite);if(n.length>=4)return{lat:(n[0]+n[2])/2,lon:(n[1]+n[3])/2,locationPrecision:'area'};n=read(b,['polygon']).split(/\s+/).map(Number).filter(Number.isFinite);if(n.length>=4){let a=0,o=0,c=0;for(let i=0;i+1<n.length;i+=2){a+=n[i];o+=n[i+1];c++}if(c)return{lat:a/c,lon:o/c,locationPrecision:'area'}}return null};
const key=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const fallback=text=>{const t=key(text);for(const k of Object.keys(centers).sort((a,b)=>b.length-a.length))if(t.includes(k))return{lat:centers[k][0],lon:centers[k][1],locationPrecision:'approx'};return null};
try{const r=await fetch(feedUrl,{headers:{accept:'application/atom+xml,application/xml,text/xml,*/*'}});if(!r.ok)throw Error('HTTP '+r.status);const xml=await r.text();const entries=xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[];const events=entries.map((b,i)=>{const title=read(b,['title','event'])||'Aviso meteorológico',area=read(b,['areaDesc','area','featureName','location']),detail=read(b,['summary','description','content']),g=geometry(b)||fallback(area+' '+title+' '+detail),time=read(b,['updated','published','effective'])||null,severity=read(b,['severity','awareness_level']),href=(b.match(/<link\b[^>]*href=["']([^"']+)["']/i)||[])[1]||feedUrl;return{id:'spain-'+i+'-'+Buffer.from(title+'|'+area+'|'+(time||'')).toString('base64url').slice(0,36),name:title,type:'weather',lat:g?.lat??null,lon:g?.lon??null,locationPrecision:g?.locationPrecision??'unknown',area,time,severity,detail:detail.slice(0,900),source:'METEOALARM-ES',scope:'spain',kind:'official',url:decode(href)}});res.setHeader('Cache-Control','s-maxage=60,stale-while-revalidate=120');return res.status(200).json({source:'METEOALARM-ES',count:events.length,events})}catch(e){return res.status(502).json({source:'METEOALARM-ES',error:String(e.message||e),events:[]})}
}